spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wareworker
    username: postgres
    password: change_me
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init.mode: always